server:
  port: 8080

clients:
  url: localhost:8081
  discount: "10%"
  cron: "0 0 * * * *"
  topic_name: "messageSMS"
  host: "localhost:9092"
  partitions: 1
  replicas: 1
  lastDigitOfNumber: "7"
  time: "19:00"

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/test_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:bigi1817}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml


